# Generated by Django 6.0.5 on 2026-05-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=10)),
                ('descripcion', models.TextField()),
                ('ubicacion_nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('is_found', models.BooleanField(default=False)),
            ],
        ),
    ]
