# Generated by Django 6.0.4 on 2026-04-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='is_found',
            field=models.BooleanField(default=False, verbose_name='¿Encontrado?'),
        ),
    ]
